name: Security (Check Vulnerabilities and Leaked Secrets Scan)

on:
  workflow_call:
    inputs:
      # With this option, only vulnerabilities of the specified level or higher are reported.
      snyk-severity-threshold:
        required: false
        type: string
        default: critical # Possible values: low, medium, high, critical
      go-version:
        required: true
        type: string

    secrets:
      LA_TECH_USER_AUTH_TOKEN:
        required: true
      LA_TECH_USER_SSH_KEY:
        required: true
      LA_SNYK_TOKEN:
        required: true

jobs:
  security:
    name: Check for vulnerabilities and secret scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Entire Git history of the repository will be fetched

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}

      # When we run snyk test it check go.mod file and list all dependencies and go through on all packages.
      # We have private repos that's why we need this step.
      - name: Setup environment to pull dependencies from non public spring-media repository
        env:
          SSH_KEY: ${{ secrets.LA_TECH_USER_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          touch  ~/.ssh/id_rsa
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 400  ~/.ssh/id_rsa
          touch ~/.ssh/config
          export location=~
          cat << EOF > ~/.ssh/config
            Host github.com
              User git
              Hostname github.com
              PreferredAuthentications publickey
              IdentityFile $location/.ssh/id_rsa
          EOF
          git config --global url."https://${{ secrets.LA_TECH_USER_AUTH_TOKEN }}:x-oauth-basic@github.com/spring-media".insteadOf "https://github.com/spring-media"

      - name: Install Snyk
        uses: snyk/actions/setup@0.4.0

      - name: Run snyk test
        run: snyk test --severity-threshold=${{ inputs.snyk-severity-threshold }}
        env:
          SNYK_TOKEN: ${{ secrets.LA_SNYK_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.LA_TECH_USER_AUTH_TOKEN }}
          GOPRIVATE: github.com/spring-media/*

      - name: Leaked Secrets Scan
        uses: trufflesecurity/trufflehog@v3.63.4
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }} # Start scanning from default main branch
          head: HEAD
          extra_args: --debug --only-verified
