name: Run e2e tests

on:
  workflow_call:
    secrets:
      CYPRESS_LOGINUSER:
        required: false
        description: Some applications need the user to be logged in. You can provide a username here that will be used for logging in to the application.
      CYPRESS_LOGINPWD:
        required: false
        description: Some applications need the user to be logged in. You can provide the password here that will be used for logging in to the application.
      NPM_AUTH_TOKEN:
        required: true
      LA_TECH_USER_AUTH_TOKEN:
        required: true

jobs:
  run-e2e-tests:
    name: Run e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          always-auth: true
          cache: npm
          registry-url: "https://registry.npmjs.org/"
      - name: Install dependencies
        run: npm install --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
          LA_TECH_USER_AUTH_TOKEN: ${{ secrets.LA_TECH_USER_AUTH_TOKEN }}
      - name: Add local.la.welt.de and local.la.spring-media.de to /etc/hosts because CORS
        run: |
          echo "127.0.0.1 local.la.welt.de" | sudo tee -a /etc/hosts
          echo "127.0.0.1 local.la.spring-media.de" | sudo tee -a /etc/hosts
      - name: Run e2e tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          command: npm run e2e
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          LA_TECH_USER_AUTH_TOKEN: ${{ secrets.LA_TECH_USER_AUTH_TOKEN }}
          NODE_TLS_REJECT_UNAUTHORIZED: 0
          CYPRESS_LOGINUSER: ${{ secrets.CYPRESS_LOGINUSER }}
          CYPRESS_LOGINPWD: ${{ secrets.CYPRESS_LOGINPWD }}
