name: Security (Check Vulnerabilities and Leaked Secrets Scan)

on:
  workflow_call:
    inputs:
      # With this option, only vulnerabilities of the specified level or higher are reported.
      snyk-severity-threshold:
        required: false
        type: string
        default: critical
    secrets:
      LA_SNYK_TOKEN:
        required: true

jobs:
  security:
    name: Check for vulnerabilities and secret scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Entire Git history of the repository will be fetched
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@0.4.0
        env:
          SNYK_TOKEN: ${{ secrets.LA_SNYK_TOKEN }}
        with:
          args: --severity-threshold=${{ inputs.snyk-severity-threshold }}
      - name: Leaked Secrets Scan
        uses: trufflesecurity/trufflehog@v3.63.4
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }} # Start scanning from default main branch
          head: ${{ github.ref_name }} # Scan the current branch
          extra_args: --debug --only-verified
