name: Configure NPM for tech user github token

on:
  workflow_call:
    secrets:
      LA_TECH_USER_AUTH_TOKEN:
        required: true
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: Configure NPM - set github token for tech user and registry
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{secrets.LA_TECH_USER_AUTH_TOKEN}}" >> .npmrc
          echo "@spring-media:registry=https://npm.pkg.github.com" >> .npmrc
     env:
        GITHUB_TOKEN: ${{ secrets.LA_TECH_USER_AUTH_TOKEN }}
