name: Format check, linting and unit tests

on:
  workflow_call:
    secrets:
      NPM_AUTH_TOKEN:
        required: true
      LA_TECH_USER_AUTH_TOKEN:
        required: true

jobs:
  format-lint-and-unit-test:
    name: Run linters and unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          always-auth: true
          cache: npm
          registry-url: "https://registry.npmjs.org/"
      - name: Setup npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{secrets.LA_TECH_USER_AUTH_TOKEN}}" >> .npmrc
          echo "@spring-media:registry=https://npm.pkg.github.com" >> .npmrc
        env:
          LA_TECH_USER_AUTH_TOKEN: ${{ secrets.LA_TECH_USER_AUTH_TOKEN }}
      - name: Install dependencies
        run: npm install --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      - name: Run format check
        run: npm run format-check
      - name: Run linters
        run: npm run lint
      - name: Run tests
        run: npm run test --if-present
